# This file was generated by the {rix} R package v0.12.4 on 2026-07-14
# with following call:
# >rix::rix(r_ver = "6f3340bf0f888d0fda9a3b91dd5b3a9b05d08212",
#  > r_pkgs = c("dplyr",
#  > "janitor",
#  > "rvest",
#  > "tidyr",
#  > "here",
#  > "ggplot2",
#  > "quarto",
#  > "targets",
#  > "tarchetypes"),
#  > system_pkgs = c("quarto"),
#  > ide = "other",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > shell_hook = "export QUARTO_R=${pkgs.R}/bin/R; unset QUARTO_PANDOC QUARTO_PATH")
# It uses nixpkgs' revision 6f3340bf0f888d0fda9a3b91dd5b3a9b05d08212 for reproducibility purposes
# which will install R version 4.4.0.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/6f3340bf0f888d0fda9a3b91dd5b3a9b05d08212.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      dplyr
      ggplot2
      here
      janitor
      quarto
      rvest
      tarchetypes
      targets
      tidyr;
  };
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      glibcLocales
      nix
      quarto
      R;
  };
  
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [  rpkgs  system_packages   ];
  shellHook = "export QUARTO_R=${pkgs.R}/bin/R; unset QUARTO_PANDOC QUARTO_PATH";
}
